name: btk_env
channels:
  - conda-forge
  - bioconda
  - tolkit
  - defaults
dependencies:
  - blast==2.12.0
  - busco==5.3.2
  - ncbi-datasets-cli==14.1.0
  - diamond==2.0.15
  - minimap2==2.24
  - blobtk==0.2.4
  - pip==22.1.2
  - python==3.9.13
  - samtools==1.15.1
  - seqtk==1.3
  - pip:
      - blobtoolkit[full]==4.1.1
