name: btk_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - blast==2.12.0
  - busco==5.3.2
  - diamond==2.0.15
  - minimap2==2.24
  - mosdepth==0.3.3
  - pigz==2.6
  - pip==22.1.2
  - python==3.9.13
  - samtools==1.15.1
  - seqtk==1.3
  - pip:
      - blobtoolkit==3.2.7
