name: btk_env
channels:
  - conda-forge
  - bioconda
  - tolkit
  - defaults
dependencies:
  - blast==2.14.0
  - busco==5.6.1
  - ncbi-datasets-cli==14.1.0
  - diamond==2.0.15
  - minimap2==2.24
  - blobtk==0.5.3
  - pip==24.2
  - python==3.10.15
  - samtools==1.15.1
  - seqtk==1.4
  - pip:
      - blobtoolkit[full]==4.3.12
