name: build-blobtoolkit

on:
  workflow_call:
    inputs:
      container-version:
        required: true
        type: string
      docker-tags:
        required: true
        type: string

jobs:
  build-blobtoolkit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Collect artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./dist
      - name: Move artifacts
        run: |
          mv dist/node/*-linux src/docker/ || true
      - name: Move pip artifacts
        run: |
          mv dist/pip/*-*-*linux*.whl src/docker/ || true
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: genomehubs/blobtoolkit
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: src/docker
          build-args: VERSION=${{ inputs.container-version }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
