name: package-host
on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      python-version:
        required: true
        type: string

jobs:
  package-python-host:
    runs-on: ubuntu-latest
    if: inputs.platform == 'linux'
    steps:
      - uses: actions/checkout@v3
      - name: Collect artifacts
        uses: actions/download-artifact@v3
        with:
          name: node
          path: ./dist
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Move viewer
        run: |
          mkdir -p ./src/blobtoolkit-host/src/data/bin
          mv ./dist/*-linux ./src/blobtoolkit-host/src/data/bin/ && chmod 755 ./src/blobtoolkit-host/src/data/bin/*-linux || exit 0
      - name: Build pip package
        working-directory: ./src/blobtoolkit-host
        run: |
          mkdir -p artifacts
          PY_VERSION=${{ inputs.python-version }}
          PY_VERSION=${PY_VERSION/./}
          python3 setup.py sdist bdist_wheel --python-tag py${PY_VERSION} --plat-name=linux_x86_64
          if [ "${{ inputs.python-version }}" == "3.9" ]; then
            pip3 install dist/blobtoolkit_host-*-py${PY_VERSION}-none-$PLATFORM.whl &&
            blobtoolkit-host -v
            mv dist/blobtoolkit*.tar.gz artifacts/
          fi
          mv dist/*.whl artifacts/
      - uses: actions/upload-artifact@v3
        with:
          name: pip
          path: ./src/blobtoolkit-host/artifacts/*

  package-python-host-macos:
    runs-on: macos-11
    if: inputs.platform == 'macos'
    steps:
      - uses: actions/checkout@v3
      - name: Collect artifacts
        uses: actions/download-artifact@v3
        with:
          name: node
          path: ./dist
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install setuptools wheel twine
          pip3 install --upgrade cython
      - name: Move viewer
        run: |
          mkdir -p ./src/blobtoolkit-host/src/data/bin
          mv ./dist/*-macos ./src/blobtoolkit-host/src/data/bin/ && chmod 755 ./src/blobtoolkit-host/src/data/bin/*-macos || exit 0
      - name: Build pip package
        working-directory: ./src/blobtoolkit-host
        run: |
          mkdir -p artifacts
          PY_VERSION=${{ inputs.python-version }}
          PY_VERSION=${PY_VERSION/./}
          python3 setup.py sdist bdist_wheel --python-tag py${PY_VERSION} --plat-name macosx_11_0_x86_64
          python3 setup.py sdist bdist_wheel --python-tag py${PY_VERSION} --plat-name macosx_11_0_arm64
          mv dist/*.whl artifacts/
      - uses: actions/upload-artifact@v3
        with:
          name: pip
          path: ./src/blobtoolkit-host/artifacts/*
