name: test-blobtoolkit
on: [push]
jobs:
  package-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install -g pkg
      - run: ./package-ui.sh
      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*

  package-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install -g pkg
      - run: ./package-api.sh
      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*

  package-blobtoolkit-linux:
    runs-on: ubuntu-latest
    needs:
      - package-ui
      - package-api
    steps:
      - uses: actions/checkout@v2
      - name: Collect artifacts
        uses: actions/download-artifact@v2
        with:
          path: ./dist
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build and publish
        run: |
          mkdir -p src/data/bin
          cp dist/artifact/*-linux src/data/bin/
          rm -r dist/artifact
          chmod 755 src/data/bin/*
          ./pip_install_latest.sh manylinux2014_x86_64
          blobtools -v
      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*

  test-commands:
    runs-on: ubuntu-latest
    needs:
      - package-blobtoolkit-linux
    steps:
      - uses: actions/checkout@v2
      - name: Collect artifacts
        uses: actions/download-artifact@v2
        with:
          path: ./dist
      - name: Pip install blobtoolkit
        run: |
          python3 -m pip install --upgrade pip
          pip install dist/artifact/*linux*.whl
          rm -r dist/artifact
          blobtools -v
      - name: Install dependencies
        run: sudo apt-get install -y chromium-browser firefox xvfb
      - run: netstat -lt
      - name: Generate static plot
        run: |
          blobtools view \
              --host http://localhost \
              --driver chromium \
              --timeout 60 \
              --ports 8000-8099 \
              --view blob \
              --param plotShape=circle \
              --param largeFonts=true \
              --format png \
              _
      - name: Test plot exists
        run: |
          test -s "FXWY01.blob.circle.png" && exit 0 || exit 1
      - uses: actions/upload-artifact@v2
        with:
          name: tests
          path: FXWY01.blob.circle.png
